### ISSUE TITLE
Autocomplete Broken - Git / FireSim Manager

### ISSUE THREAD

**Issue by abejgonzalez** [firesim/firesim#1039]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

Release: N/A
Hash: 68b0938

### OS Setup

Whatever AMI is specified on `main`. Default setup.

### Other Setup

Default setup of a FireSim manager.

### Current Behavior

There is no autocomplete for things like `git` and the `firesim` command. 

### Expected Behavior

I expect to have autocomplete for things like `git` and the `firesim` command.

### Other Information

I think with the bump to conda (and change in `machine-launch-script.sh`) this broke - #986

**Comment by timsnyder-siv** [comment]
Can you share the output you get from `complete -p` in a shell where completion was working the way you wanted it to and what you see now?

**Comment by timsnyder-siv** [comment]
Looking into this a bit more, the old yum-based machine-launch-script.sh installed `bash-completion` from yum and this adds the toplevel `/etc/profile.d/bash_completion.sh` which enables all of the completions in `/etc/bash_completion.d/`.

There is a `bash-completion` conda package that can be added into our environment and that will make git start working.  I'm not sure what it looks like for firesim completion to be "working" because I've never had it work for me.  I'll open a PR with some changes that you can try.
