### ISSUE TITLE
Fatal Error at firesim launchrunfarm

### ISSUE THREAD

**Issue by redpanda3** [firesim/firesim#269]
FireSim Manager. Docs: http://docs.fires.im
Running: launchrunfarm

Fatal error.
Traceback (most recent call last):
  File "/home/centos/src/project_data/firesim/deploy/firesim", line 307, in <module>
    main(args)
  File "/home/centos/src/project_data/firesim/deploy/firesim", line 253, in main
    simconf = RuntimeConfig(args)
  File "/home/centos/src/project_data/firesim/deploy/runtools/runtime_config.py", line 292, in __init__
    args.overrideconfigdata)
  File "/home/centos/src/project_data/firesim/deploy/runtools/runtime_config.py", line 260, in __init__
    self.profileinterval = int(runtime_dict['targetconfig']['profileinterval'])
KeyError: 'profileinterval'
The full log of this run is:

**Comment by redpanda3** [comment]
The log file is as above.

**Comment by redpanda3** [comment]
OK, let me have a try...

**Comment by redpanda3** [comment]
FireSim Manager. Docs: http://docs.fires.im
Running: launchrunfarm

Fatal error.
Traceback (most recent call last):
  File "/home/centos/src/project_data/firesim/deploy/firesim", line 307, in <module>
    main(args)
  File "/home/centos/src/project_data/firesim/deploy/firesim", line 253, in main
    simconf = RuntimeConfig(args)
  File "/home/centos/src/project_data/firesim/deploy/runtools/runtime_config.py", line 320, in __init__
    self.innerconf.terminateoncompletion)
  File "/home/centos/src/project_data/firesim/deploy/runtools/firesim_topology_with_passes.py", line 56, in __init__
    self.phase_one_passes()
  File "/home/centos/src/project_data/firesim/deploy/runtools/firesim_topology_with_passes.py", line 317, in phase_one_passes
    self.pass_apply_default_hwconfig()
  File "/home/centos/src/project_data/firesim/deploy/runtools/firesim_topology_with_passes.py", line 263, in pass_apply_default_hwconfig
    defaulthwconfig_obj = self.hwdb.get_runtimehwconfig_from_name(self.defaulthwconfig)
  File "/home/centos/src/project_data/firesim/deploy/runtools/runtime_config.py", line 218, in get_runtimehwconfig_from_name
    return self.hwconf_dict[name]
KeyError: 'firesim-quadcore-no-nic-ddr3-llc4mb'
The full log of this run is:
/home/centos/src/project_data/firesim/deploy/logs/2019-04-01--22-40-31-launchrunfarm-7Z12LUEVRM2WJWL5.log   

And I have tried singlecore, still have the key error problem. 

My config file 

# RUNTIME configuration for the FireSim Simulation Manager
# See docs/Configuration-Details.rst for documentation of all of these params.

[runfarm]
runfarmtag=mainrunfarm

f1_16xlarges=0
f1_4xlarges=1
m4_16xlarges=0
f1_2xlarges=1

runinstancemarket=ondemand
spotinterruptionbehavior=terminate
spotmaxprice=ondemand

[targetconfig]
topology=no_net_config
no_net_num_nodes=1
linklatency=6405
switchinglatency=10
netbandwidth=200
profileinterval = -1

# This references a section from config_hwconfigs.ini
# In homogeneous configurations, use this to set the hardware config deployed
# for all simulators
defaulthwconfig=firesim-quadcore-no-nic-ddr3-llc4mb

[tracing]
enable = no
startcycle = 0
endcycle = -1


[workload]
workloadname=linux-uniform.json
terminateoncompletion=no



@davidbiancolin

**Comment by davidbiancolin** [comment]
This is a different error than last time. Did you bump recently? You might have to run
`firesim managerinit` to re-copy the sample inis. 

That error says it can't find the hwdb entry named "firesim-quadcore-no-nic-ddr3-llc4mb". Confirm it exists in config_hwdb.ini.

**Comment by redpanda3** [comment]
OK

**Comment by redpanda3** [comment]
`FireSim Manager. Docs: http://docs.fires.im
Running: launchrunfarm

An error occurred (InvalidParameter) when calling the RunInstances operation: Security group sg-08fb5a385dbc07fa1 and subnet subnet-0d6a205f87324418e belong to different networks.
This probably means there was no more capacity in this availability zone. Try the next one.
An error occurred (InvalidParameter) when calling the RunInstances operation: Security group sg-08fb5a385dbc07fa1 and subnet subnet-082d1684cdcd48d82 belong to different networks.
This probably means there was no more capacity in this availability zone. Try the next one.
An error occurred (InvalidParameter) when calling the RunInstances operation: Security group sg-08fb5a385dbc07fa1 and subnet subnet-0949e9cd01f4e6b75 belong to different networks.
This probably means there was no more capacity in this availability zone. Try the next one.
we tried all subnets, but there was insufficient capacity to launch your instances
only the following 0 instances were launched
[]
Fatal error.
Traceback (most recent call last):
  File "/home/centos/src/project_data/firesim/deploy/firesim", line 307, in <module>
    main(args)
  File "/home/centos/src/project_data/firesim/deploy/firesim", line 255, in main
    globals()[args.task](simconf)
  File "/home/centos/src/project_data/firesim/deploy/firesim", line 139, in launchrunfarm
    runtime_conf.runfarm.launch_run_farm()
  File "/home/centos/src/project_data/firesim/deploy/runtools/run_farm.py", line 241, in launch_run_farm
    wait_on_instance_launches(f1_16s, 'f1.16xlarges')
  File "/home/centos/src/project_data/firesim/deploy/awstools/awstools.py", line 206, in wait_on_instance_launches
    rootLogger.info("Waiting for instance boots: " + str(len(instances)) + " " + message)
TypeError: object of type 'NoneType' has no len()
`
This is after I run firesim managerinit, and firesim launchfram. Here is my config_runtime.


[runfarm]
runfarmtag=mainrunfarm

f1_16xlarges=1
m4_16xlarges=0
f1_4xlarges=0
f1_2xlarges=0

runinstancemarket=ondemand
spotinterruptionbehavior=terminate
spotmaxprice=ondemand

[targetconfig]
topology=example_8config
no_net_num_nodes=2
linklatency=6405
switchinglatency=10
netbandwidth=200
profileinterval=-1

defaulthwconfig=firesim-quadcore-nic-ddr3-llc4mb

[tracing]
enable=no
startcycle=0
endcycle=-1

[workload]
workloadname=linux-uniform.json
terminateoncompletion=no

I still have f1x16 limits. And I have quadcore in config_hwdb.

@davidbiancolin

**Comment by davidbiancolin** [comment]
Did you bump recently? Or is this a fresh build?

It seems like you might have misconfigured your manager instance when doing initial setup. @sagark do you have a read on this?

**Comment by sagark** [comment]
Did you run the aws-setup.py script multiple times? My guess is that if you look at your list of VPCs and security groups, there will be multiple that are named "firesim". The security groups belong to a particular VPC, so when the manager looks for a VPC and security group by the name "firesim" it happens to be getting the "firesim" security group that isn't for the "firesim" VPC it's defaulting to. You should delete one pair of these if this is the case. Let us know if that isn't it @redpanda3

**Comment by redpanda3** [comment]
@sagark Maybe I can come to your office some day.

**Comment by redpanda3** [comment]
@sagark Should I delete one firesim group and start a new manager instance? Or all firesim groups, and start from the t.nano? I only has one firesim group.

**Comment by sagark** [comment]
@redpanda3 I responded to your email, let's continue this there.

**Comment by davidbiancolin** [comment]
Closing, as it looks like this was resolved out-of-band.

**Comment by JaewonHur** [comment]
Hi, I'm new to firesim and I'm following the tutorial in firesim documentation (Running a single node simulation).
I followed all the instructions and I also get the required instances (two c5.4xlarge and one f1.2xlarge)
But `firesim launchrunfarm` fails because the f1.2xlarge instance is allocated to the different availability zone.

Does anyone know how to solve this?
Below is the log.

> /usr/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by t│
he Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.                │
  from cryptography.hazmat.backends import default_backend                                                                     │
FireSim Manager. Docs: http://docs.fires.im                                                                                    │
Running: launchrunfarm                                                                                                         │
                                                                                                                               │
An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (f1.2xlarge) is not suppo│
rted in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choo│
sing us-west-2a, us-west-2b, us-west-2c.                                                                                       │
This probably means there was no more capacity in this availability zone. Try the next one.                                    │
Waiting for instance boots: 0 f1.16xlarges                                                                                     │
Waiting for instance boots: 0 f1.4xlarges                                                                                      │
Waiting for instance boots: 0 m4.16xlarges                                                                                     │
Waiting for instance boots: 1 f1.2xlarges                                                                                      │
i-02c0a969a533f3543 booted!                                                                                                    │
The full log of this run is:                                                                                                   │
/home/centos/firesim/deploy/logs/2020-09-18--03-03-32-launchrunfarm-QSTRUMFU34BD7DFP.log
