### ISSUE TITLE
Discrepancy in mcycle/RTC behavior between GoldenGate SW sim and FireSim FPGA sim

### ISSUE THREAD

**Issue by zhemao** [firesim/firesim#407]
Running the check-rtc workload in GoldenGate VCS simulation gives a different result from when it is run on the FPGA.

Steps to run in VCS

    cd sw/check-rtc && make check-rtc
    cd ../../sim && make run-vcs SIM_BINARY=../sw/check-rtc/check-rtc

Steps to run in FireSim

1. Set `workloadname` in deploy/config_runtime.ini to "check-rtc.json"
2. Run `make check-rtc` in deploy/workloads
3. Run firesim infrasetup/runworkload

**Comment by davidbiancolin** [comment]
Following up on this, this discrepancy emerges because FESVR polls the target at a considerably slower frequency on the FPGA vs in ML simulation. The benchmark reports the same number of cycles per jiffy when the same polling interval is used. 

#474 makes it so that copying the same +args from the FPGA simulator to the midas-level simulator should produce the same results.
