### ISSUE TITLE
ERROR: Vivado v2021.1 (64-bit) is not supported by this HDK release.  

### ISSUE THREAD

**Issue by vargandhi** [firesim/firesim#980]
Hi, 

I'm trying to setup a new manager instance using chipyard. My ec2 instance uses the new AMI, i.e.,  FPGA Developer AMI - 1.11.1-40257ab5-6688-4c95-97d1-e251a40fd1fc. However, I get the following error when I run "./scripts/firesim-setup.sh --fast":

ERROR: Vivado v2021.1 (64-bit) is not supported by this HDK release.                                                                    
ERROR: Supported versions are:                                                                                                          
Vivado v2017.4 (64-bit)                                                                                                                 
Vivado v2017.4.op (64-bit)                                                                                                              
Vivado v2018.2_AR71275_op (64-bit)                                                                                                      
Vivado v2018.2_AR71715 (64-bit)                                                                                                         
Vivado v2018.2.op (64-bit)                                                                                                              
Vivado v2018.2 (64-bit)                                                                                                                 
Vivado v2018.3.op (64-bit)                                                                                                              
Vivado v2018.3 (64-bit)
-----------------------
I have never seen this error before. Would appreciate some insights. thanks!

**Comment by timsnyder** [comment]
Hi Varun,

It sounds like you're using the new FPGA Developer AMI with an older
version of Chipyard->Firesim->aws-fpga.  If I start from Chipyard's main
branch right now and traverse via the GH web UI through
sim/firesim/platforms/f1/aws-fpga/supported_vivado_versions.txt I see
v2021.1 in the list here:
https://github.com/firesim/aws-fpga-firesim/blob/0a4b5b6b3a82c00f25a6df4423d90d1a0a673f6b/supported_vivado_versions.txt

If for some reason, you need to use older Chipyard&Firesim, you should look
at sim/firesim/deploy/awstools/awstools.py and the AMI version you need to
use with that version of FireSim will be contained in a variable near the
top of the file called f1_ami_name.
https://github.com/firesim/firesim/blob/a0f78b1cd081b1199acbfaa588a13b1f41ea26fa/deploy/awstools/awstools.py#L29

Otherwise, you should probably consider using the latest release version of
Chipyard 1.6.2 https://github.com/ucb-bar/chipyard/releases/tag/1.6.2

Cheers,
-Tim
